# Copyright 2026 Siddharth
# SPDX-License-Identifier: Apache-2.0

"""Markdown audit report rendering."""

from __future__ import annotations

from datetime import datetime, timezone

from jinja2 import Environment

from .store import SEVERITY_ORDER, Action, Finding, Session, Store

_TEMPLATE = """# Anzen Audit Report — {{ session.id }}

**Agent:** {{ session.agent_name }}
**Started:** {{ started }}
**Duration:** {{ duration }}
**Actions recorded:** {{ actions | length }}
**Token usage:** {{ session.input_tokens }} in / {{ session.output_tokens }} out
**Findings:** {{ findings | length }}{% if severity_summary %} ({{ severity_summary }}){% endif %}

---

## Findings

{% if not findings %}No policy violations were detected in this session.
{% else %}{% for f in findings %}
### {{ loop.index }}. {{ sev_icon(f.severity) }} [{{ f.severity | upper }}] {{ f.title }}

- **Rule:** `{{ f.rule_id }}`{% if f.owasp_llm %} · **OWASP:** {{ f.owasp_llm }}{% endif %} · **Source:** {{ f.source }}
{% if f.action_id %}- **Action:** {{ action_label(f.action_id) }}{% endif %}

**What happened**
{{ f.explanation | trim }}
{% if f.matched_excerpt %}
> Matched: `{{ f.matched_excerpt }}`
{% endif %}
**How to fix it**
{{ f.remediation | trim }}

---
{% endfor %}{% endif %}

## Action timeline

| # | Time | Type | Name | Status | Findings |
|---|------|------|------|--------|----------|
{% for a in actions %}| {{ loop.index }} | {{ ts(a.timestamp) }} | {{ a.action_type.value }} | {{ a.name | truncate(40) }} | {{ a.status }} | {{ finding_marks(a.id) }} |
{% endfor %}

<sub>Generated by Anzen at {{ now }}.</sub>
"""

_SEV_ICON = {
    "critical": "🟥",
    "high": "🟧",
    "medium": "🟨",
    "low": "🟦",
    "info": "⬜",
}


def _fmt_ts(value: float | None) -> str:
    if not value:
        return "—"
    return datetime.fromtimestamp(value, tz=timezone.utc).strftime("%H:%M:%S")


def render_markdown(session: Session, actions: list[Action], findings: list[Finding]) -> str:
    action_by_id = {a.id: a for a in actions}
    marks_by_action: dict[int, list[str]] = {}
    for f in findings:
        if f.action_id is not None:
            marks_by_action.setdefault(f.action_id, []).append(_SEV_ICON.get(f.severity, "•"))

    counts: dict[str, int] = {}
    for f in findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
    severity_summary = ", ".join(
        f"{counts[s]} {s}" for s in SEVERITY_ORDER if s in counts
    )

    duration = "—"
    if session.started_at and session.ended_at:
        duration = f"{session.ended_at - session.started_at:.2f}s"

    def action_label(action_id: int) -> str:
        a = action_by_id.get(action_id)
        if not a:
            return f"#{action_id}"
        idx = list(action_by_id).index(action_id) + 1
        return f"#{idx} {a.action_type.value} `{a.name}`"

    def finding_marks(action_id: int | None) -> str:
        return " ".join(marks_by_action.get(action_id, [])) if action_id else ""

    env = Environment(autoescape=False, trim_blocks=False, lstrip_blocks=False)
    template = env.from_string(_TEMPLATE)
    return template.render(
        session=session,
        actions=actions,
        findings=findings,
        started=_fmt_ts(session.started_at),
        duration=duration,
        severity_summary=severity_summary,
        now=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        sev_icon=lambda s: _SEV_ICON.get(s, "•"),
        ts=_fmt_ts,
        action_label=action_label,
        finding_marks=finding_marks,
    )


def build_report(store: Store, session_id: str) -> tuple[Session, str]:
    session = store.get_session(session_id)
    if session is None:
        raise KeyError(session_id)
    actions = store.get_actions(session.id)
    findings = store.get_findings(session.id)
    return session, render_markdown(session, actions, findings)
